In [3]:
from google.colab import files
file = files.upload()

Saving Transaction_Data.xlsx to Transaction_Data (1).xlsx

In [4]:
import pandas as pd

In [5]:
transaction_data = pd.read_excel('/content/Transaction_Data.xlsx')

In [6]:
transaction_data

,Customer_ID,Order #,Date,Product(s),Items sold,Revenue,Net_Sales,Status
0,CUS000001,157518,2024-08-29 12:50:44,1× Garri Processing Plant (Combo) - Locally As...,1,8880000.0,8700000.0,completed
1,CUS000002,84663,2022-01-12 14:52:40,8× AGRITED Pullets (Hyline Brown Pullets) Day-Old,8,170800.0,162000.0,completed
2,CUS000002,109382,2023-04-14 12:46:29,1× AMO Broiler Chicks | Day-Old Birds,1,8450.0,7150.0,completed
3,CUS000003,158497,2024-09-11 13:50:03,1× Papaya Nouna F1,1,13500.0,11500.0,completed
4,CUS000003,162523,2024-10-28 14:36:11,5× Maradona F1 (Dwarf Papaya | 100 Seeds),5,121000.0,120000.0,completed
...,...,...,...,...,...,...,...,...
16451,CUS003120,68918,2021-01-18 10:27:32,2× Paper Egg Crates (White | Brown | Bundle of...,2,9000.0,9000.0,completed
16452,CUS003120,70707,2021-02-23 09:32:16,1× Chicken/Meat Cutter (Electric Powered) - Promo,1,360000.0,360000.0,completed
16453,CUS003121,146704,2024-05-08 08:49:18,1× Seed/Fertilizer Planter + Oba Super-6 Maize...,1,167500.0,155000.0,completed
16454,CUS003122,77451,2021-08-11 13:25:07,NaN,25,437500.0,437500.0,completed
16455,CUS003122,79871,2021-10-04 08:10:30,NaN,1,165000.0,165000.0,completed

In [7]:
def clean_product_column(product_str):
    if isinstance(product_str, str):
        product_list = []
        for product in product_str.split(','):
            cleaned_product = product.split('×')[-1].strip()
            cleaned_product = cleaned_product.split('|')[0].strip()
            product_list.append(cleaned_product)
        return product_list
    else:
        return product_str

transaction_data['Cleaned_Products'] = transaction_data['Product(s)'].apply(clean_product_column)

max_products = transaction_data['Cleaned_Products'].apply(lambda x: len(x) if isinstance(x, list) else 0).max()

for i in range(1, max_products + 1):
    transaction_data[f'Product_{i}'] = transaction_data['Cleaned_Products'].apply(lambda x: x[i-1] if isinstance(x, list) and len(x) >= i else None)

transaction_data.head()

,Customer_ID,Order #,Date,Product(s),Items sold,Revenue,Net_Sales,Status,Cleaned_Products,Product_1,...,Product_13,Product_14,Product_15,Product_16,Product_17,Product_18,Product_19,Product_20,Product_21,Product_22
0,CUS000001,157518,2024-08-29 12:50:44,1× Garri Processing Plant (Combo) - Locally As...,1,8880000.0,8700000.0,completed,[Garri Processing Plant (Combo) - Locally Asse...,Garri Processing Plant (Combo) - Locally Assem...,...,None,None,None,None,None,None,None,None,None,None
1,CUS000002,84663,2022-01-12 14:52:40,8× AGRITED Pullets (Hyline Brown Pullets) Day-Old,8,170800.0,162000.0,completed,[AGRITED Pullets (Hyline Brown Pullets) Day-Old],AGRITED Pullets (Hyline Brown Pullets) Day-Old,...,None,None,None,None,None,None,None,None,None,None
2,CUS000002,109382,2023-04-14 12:46:29,1× AMO Broiler Chicks | Day-Old Birds,1,8450.0,7150.0,completed,[AMO Broiler Chicks],AMO Broiler Chicks,...,None,None,None,None,None,None,None,None,None,None
3,CUS000003,158497,2024-09-11 13:50:03,1× Papaya Nouna F1,1,13500.0,11500.0,completed,[Papaya Nouna F1],Papaya Nouna F1,...,None,None,None,None,None,None,None,None,None,None
4,CUS000003,162523,2024-10-28 14:36:11,5× Maradona F1 (Dwarf Papaya | 100 Seeds),5,121000.0,120000.0,completed,[Maradona F1 (Dwarf Papaya],Maradona F1 (Dwarf Papaya,...,None,None,None,None,None,None,None,None,None,None

In [41]:
!pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [8]:
transaction_data.to_excel("Transaction_data_clean.xlsx",index=False)

In [9]:
transaction_data_clean = pd.read_excel('/content/Transaction_data_clean.xlsx')

In [44]:
transaction_data_clean

,Customer_ID,Order #,Date,Product(s),Items sold,Revenue,Net_Sales,Status,Cleaned_Products,Product_1,...,Product_13,Product_14,Product_15,Product_16,Product_17,Product_18,Product_19,Product_20,Product_21,Product_22
0,CUS000001,157518,2024-08-29 12:50:44,1× Garri Processing Plant (Combo) - Locally As...,1,8880000.0,8700000.0,completed,['Garri Processing Plant (Combo) - Locally Ass...,Garri Processing Plant (Combo) - Locally Assem...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CUS000002,84663,2022-01-12 14:52:40,8× AGRITED Pullets (Hyline Brown Pullets) Day-Old,8,170800.0,162000.0,completed,['AGRITED Pullets (Hyline Brown Pullets) Day-O...,AGRITED Pullets (Hyline Brown Pullets) Day-Old,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CUS000002,109382,2023-04-14 12:46:29,1× AMO Broiler Chicks | Day-Old Birds,1,8450.0,7150.0,completed,['AMO Broiler Chicks'],AMO Broiler Chicks,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CUS000003,158497,2024-09-11 13:50:03,1× Papaya Nouna F1,1,13500.0,11500.0,completed,['Papaya Nouna F1'],Papaya Nouna F1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CUS000003,162523,2024-10-28 14:36:11,5× Maradona F1 (Dwarf Papaya | 100 Seeds),5,121000.0,120000.0,completed,['Maradona F1 (Dwarf Papaya'],Maradona F1 (Dwarf Papaya,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16451,CUS003120,68918,2021-01-18 10:27:32,2× Paper Egg Crates (White | Brown | Bundle of...,2,9000.0,9000.0,completed,['Paper Egg Crates (White'],Paper Egg Crates (White,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16452,CUS003120,70707,2021-02-23 09:32:16,1× Chicken/Meat Cutter (Electric Powered) - Promo,1,360000.0,360000.0,completed,['Chicken/Meat Cutter (Electric Powered) - Pro...,Chicken/Meat Cutter (Electric Powered) - Promo,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16453,CUS003121,146704,2024-05-08 08:49:18,1× Seed/Fertilizer Planter + Oba Super-6 Maize...,1,167500.0,155000.0,completed,['Seed/Fertilizer Planter + Oba Super-6 Maize ...,Seed/Fertilizer Planter + Oba Super-6 Maize Se...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16454,CUS003122,77451,2021-08-11 13:25:07,NaN,25,437500.0,437500.0,completed,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16455,CUS003122,79871,2021-10-04 08:10:30,NaN,1,165000.0,165000.0,completed,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data preparation


Prepare the `transaction_data` for building a recommendation model. This may involve tasks such as creating a user-item matrix or other suitable data structures.

**Reasoning**:
Prepare the data for the recommendation model by creating a user-item matrix. This involves selecting relevant columns, melting the data, handling missing values, and creating a pivot table.

In [10]:
product_data = transaction_data_clean[['Customer_ID'] + [f'Product_{i}' for i in range(1, 23)]]

melted_product_data = product_data.melt(id_vars=['Customer_ID'], value_name='Product')

melted_product_data.dropna(subset=['Product'], inplace=True)

user_item_matrix = melted_product_data.pivot_table(index='Customer_ID', columns='Product', aggfunc='size', fill_value=0)

display(user_item_matrix.head())

Product,"""KAAS-TOLTRA 250",(Organic Fertilizer and Soil Conditioner,000 Seeds,000 Seeds - 10 bags and above,000 Seeds - Below 10 bags,000),000) - brooder-guard-gas-brooder-htc-digital-thermometer-biovitastress,000) - gas-brooder-htc-digital-thermometer,080 Chicken Egg Capacity KGE Incubator Powered by Kerosene/Gas/Electricity/Solar Power - 120M96 Model - Incubator+Candling machine+Solar arrangement,10,...,five-DICLACOX,five-IODINE,five-MIX,five-TETRAVIT EGGS,it quickly kills pests while soothing irritated birds. Ideal for all climates,mites,more productive flock! (Copy),natural lemon,this easy-to-use powder improves feeding efficiency,with Imported PVC Feeders
Customer_ID,,,,,,,,,,,,,,,,,,,,,
CUS000001,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CUS000002,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CUS000003,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CUS000004,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
CUS000005,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Model selection

Choose an appropriate recommendation model based on the data and the goal of generating personalized recommendations.

**Reasoning**:
Based on the binary nature of the user-item matrix and the goal of generating personalized recommendations using implicit feedback, a suitable collaborative filtering model is needed. Matrix Factorization models like Singular Value Decomposition (SVD) are well-suited for this as they can capture latent features that explain the observed purchases and predict potential future purchases. Since we are dealing with implicit feedback (purchase or no purchase), techniques like Funk SVD or algorithms designed for implicit data such as LightFM could be considered. Given the available data in the form of a user-item matrix, implementing a basic SVD-based approach will be appropriate to derive latent factors for users and items.

In [11]:
print("A suitable recommendation model for this binary user-item matrix with implicit feedback is a Matrix Factorization model, such as Singular Value Decomposition (SVD).")
print("SVD works by decomposing the user-item matrix into two lower-rank matrices, one representing latent features for users and the other for items.")
print("These latent features capture underlying preferences of users and characteristics of items that explain the observed purchase behavior.")
print("For implicit feedback data like this, where the values represent purchases (1) and non-purchases (0), SVD-based methods can learn to predict the likelihood of a user interacting with an item they haven't purchased yet.")
print("This aligns well with the goal of generating personalized product recommendations by identifying items a user is likely to purchase based on their past behavior and the behavior of similar users.")

A suitable recommendation model for this binary user-item matrix with implicit feedback is a Matrix Factorization model, such as Singular Value Decomposition (SVD).
SVD works by decomposing the user-item matrix into two lower-rank matrices, one representing latent features for users and the other for items.
These latent features capture underlying preferences of users and characteristics of items that explain the observed purchase behavior.
For implicit feedback data like this, where the values represent purchases (1) and non-purchases (0), SVD-based methods can learn to predict the likelihood of a user interacting with an item they haven't purchased yet.
This aligns well with the goal of generating personalized product recommendations by identifying items a user is likely to purchase based on their past behavior and the behavior of similar users.

## Model training

Train the selected model using the prepared data.

**Reasoning**:
Import necessary classes from surprise and prepare the data for training the SVD model.

In [12]:
!pip install surprise

Requirement already satisfied: surprise in /usr/local/lib/python3.12/dist-packages (0.1)
Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.12/dist-packages (from surprise) (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise->surprise) (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise->surprise) (1.26.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise->surprise) (1.16.2)

**Reasoning**:
Import necessary classes from surprise and prepare the data for training the SVD model, then instantiate and train the SVD model.

In [13]:
!pip install numpy==1.26.0

Requirement already satisfied: numpy==1.26.0 in /usr/local/lib/python3.12/dist-packages (1.26.0)

In [16]:
product_data = transaction_data_clean[['Customer_ID'] + [f'Product_{i}' for i in range(1, 23)]]

melted_product_data = product_data.melt(id_vars=['Customer_ID'], value_name='Product')

melted_product_data.dropna(subset=['Product'], inplace=True)

melted_product_data['Purchase'] = 1

from surprise import Dataset, Reader, SVD

reader = Reader(rating_scale=(0, 1))
data = Dataset.load_from_df(melted_product_data[['Customer_ID', 'Product', 'Purchase']], reader)

trainset = data.build_full_trainset()

model = SVD()

model.fit(trainset)

## Prediction

Use the trained model to generate personalized product recommendations for each customer.

**Reasoning**:
Get unique customer IDs and product names, and then iterate through each customer and each product they haven't purchased to predict the purchase likelihood using the trained SVD model. Store these predictions in a list of tuples and convert to a pandas DataFrame.

In [17]:
unique_customer_ids = user_item_matrix.index.unique()
unique_product_names = user_item_matrix.columns.unique()

predictions = []
for customer_id in unique_customer_ids:
    purchased_products = user_item_matrix.loc[customer_id][user_item_matrix.loc[customer_id] > 0].index.tolist()
    for product_name in unique_product_names:
        if product_name not in purchased_products:
            predicted_likelihood = model.predict(customer_id, product_name, r_ui=0).est
            predictions.append((customer_id, product_name, predicted_likelihood))

predictions_df = pd.DataFrame(predictions, columns=['Customer_ID', 'Product', 'Predicted_Likelihood'])
display(predictions_df.head())

  Customer_ID                                   Product  Predicted_Likelihood
0   CUS000001                          "KAAS-TOLTRA 250              0.968334
1   CUS000001  (Organic Fertilizer and Soil Conditioner              0.971624
2   CUS000001                                 000 Seeds              0.927826
3   CUS000001             000 Seeds - 10 bags and above              0.961433
4   CUS000001                 000 Seeds - Below 10 bags              1.000000

**Reasoning**:
For each customer, sort the predicted products by their likelihood in descending order and select the top N recommendations (N=10), then combine the top recommendations for all customers into a single DataFrame.

In [18]:
top_n_recommendations = predictions_df.groupby('Customer_ID').apply(lambda x: x.nlargest(10, 'Predicted_Likelihood')).reset_index(drop=True)
display(top_n_recommendations.head())

/tmp/ipython-input-2067149460.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_n_recommendations = predictions_df.groupby('Customer_ID').apply(lambda x: x.nlargest(10, 'Predicted_Likelihood')).reset_index(drop=True)

,Customer_ID,Product,Predicted_Likelihood
0,CUS000001,000 Seeds - Below 10 bags,1.0
1,CUS000001,000),1.0
2,CUS000001,10-12cm (Jumbo),1.0
3,CUS000001,1000kg Digital Floor Weighing Scale (A12E-Camr...,1.0
4,CUS000001,1056 Eggs Capacity Incubators (Electric Powere...,1.0

## Save predictions

Save the generated recommendations to a CSV file that can be easily imported into Tableau for visualization.

In [19]:
top_n_recommendations.to_csv('top_n_recommendations.csv', index=False)